In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("salary_synthetic.csv")
df

,age,gender,education,experience_years,role_seniority,company_size,location_tier,skills_count,certifications,worked_remote,last_promotion_years_ago,salary_bdt,recent_project_description_length,survey_date,recent_note
0,33,Male,M.Sc,6.0,Senior,Enterprise,Tier-2,1.0,2.0,1,0.0,145185,57.0,2024-11-15,Worked on microservices deployment
1,29,Male,M.Sc,9.0,Junior,Enterprise,Remote,5.0,0.0,1,0.0,121262,50.0,2024-03-08,Built ML pipeline for preprocessing
2,34,Male,B.Sc+Cert,NaN,Lead,Enterprise,Remote,5.0,1.0,1,5.0,184875,50.0,2024-09-01,Experience in data cleaning and ETL
3,39,Male,B.Sc,16.0,Mid,Enterprise,Tier-1,5.0,0.0,1,3.0,180105,59.0,2024-01-26,Contributed to open-source NLP repo
4,29,Female,B.Sc,8.0,Junior,SME,Tier-1,5.0,2.0,0,7.0,114750,NaN,2023-12-08,Built ML pipeline for preprocessing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,36,Male,B.Sc,17.0,Junior,Enterprise,Tier-3,7.0,1.0,0,2.0,199330,84.0,2023-03-02,NaN
1996,30,Male,B.Sc,5.0,Mid,Startup,Remote,6.0,0.0,1,3.0,88626,53.0,2024-03-10,Built ML pipeline for preprocessing
1997,25,Female,B.Sc,0.0,Junior,Startup,Tier-1,1.0,1.0,0,0.0,32276,64.0,2023-12-05,Worked on microservices deployment
1998,29,Male,M.Sc,2.0,Senior,Enterprise,Remote,5.0,1.0,0,1.0,103449,49.0,2023-09-26,NaN
1999,26,Male,B.Sc,1.0,Mid,Enterprise,Tier-1,4.0,1.0,0,3.0,69299,54.0,2023-01-08,Contributed to open-source NLP repo

In [5]:
df.head()

,age,gender,education,experience_years,role_seniority,company_size,location_tier,skills_count,certifications,worked_remote,last_promotion_years_ago,salary_bdt,recent_project_description_length,survey_date,recent_note
0,33,Male,M.Sc,6.0,Senior,Enterprise,Tier-2,1.0,2.0,1,0.0,145185,57.0,2024-11-15,Worked on microservices deployment
1,29,Male,M.Sc,9.0,Junior,Enterprise,Remote,5.0,0.0,1,0.0,121262,50.0,2024-03-08,Built ML pipeline for preprocessing
2,34,Male,B.Sc+Cert,NaN,Lead,Enterprise,Remote,5.0,1.0,1,5.0,184875,50.0,2024-09-01,Experience in data cleaning and ETL
3,39,Male,B.Sc,16.0,Mid,Enterprise,Tier-1,5.0,0.0,1,3.0,180105,59.0,2024-01-26,Contributed to open-source NLP repo
4,29,Female,B.Sc,8.0,Junior,SME,Tier-1,5.0,2.0,0,7.0,114750,NaN,2023-12-08,Built ML pipeline for preprocessing

In [6]:
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Number of Rows: 2000
Number of Columns: 15

In [7]:
print("Column Names:")
print(df.columns.tolist())

Column Names:
['age', 'gender', 'education', 'experience_years', 'role_seniority', 'company_size', 'location_tier', 'skills_count', 'certifications', 'worked_remote', 'last_promotion_years_ago', 'salary_bdt', 'recent_project_description_length', 'survey_date', 'recent_note']

In [8]:
print(df.dtypes)

age                                    int64
gender                                   str
education                                str
experience_years                     float64
role_seniority                           str
company_size                             str
location_tier                            str
skills_count                         float64
certifications                       float64
worked_remote                          int64
last_promotion_years_ago             float64
salary_bdt                             int64
recent_project_description_length    float64
survey_date                              str
recent_note                              str
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   age                                2000 non-null   int64
 1   gender                             2000 non-null   str
 2   education                          1900 non-null   str
 3   experience_years                   1840 non-null   float64
 4   role_seniority                     2000 non-null   str
 5   company_size                       2000 non-null   str
 6   location_tier                      2000 non-null   str
 7   skills_count                       1800 non-null   float64
 8   certifications                     1920 non-null   float64
 9   worked_remote                      2000 non-null   int64
 10  last_promotion_years_ago           1880 non-null   float64
 11  salary_bdt                         2000 non-null   int64
 12  recent_project_description_length  1760 non-null   float64
 13  survey_date                        2000 non-null   str
 14  recent_note                        1700 non-null   str
dtypes: float64(5), int64(3), str(7)
memory usage: 360.9 KB

In [10]:
missing_values = df.isnull().sum()
print(missing_values)

age                                    0
gender                                 0
education                            100
experience_years                     160
role_seniority                         0
company_size                           0
location_tier                          0
skills_count                         200
certifications                        80
worked_remote                          0
last_promotion_years_ago             120
salary_bdt                             0
recent_project_description_length    240
survey_date                            0
recent_note                          300
dtype: int64

In [11]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": missing_percentage
})
missing_summary

                                   Missing_Count  Missing_Percentage
age                                            0                 0.0
gender                                         0                 0.0
education                                    100                 5.0
experience_years                             160                 8.0
role_seniority                                 0                 0.0
company_size                                   0                 0.0
location_tier                                  0                 0.0
skills_count                                 200                10.0
certifications                                80                 4.0
worked_remote                                  0                 0.0
last_promotion_years_ago                     120                 6.0
salary_bdt                                     0                 0.0
recent_project_description_length            240                12.0
survey_date                                    0                 0.0
recent_note                                  300                15.0

In [12]:
numerical_columns = df.select_dtypes(include=np.number).columns.tolist()

print("Numerical Columns:")
print(numerical_columns)

Numerical Columns:
['age', 'experience_years', 'skills_count', 'certifications', 'worked_remote', 'last_promotion_years_ago', 'salary_bdt', 'recent_project_description_length']

In [13]:
categorical_columns = [
    "gender",
    "education",
    "role_seniority",
    "company_size",
    "location_tier"
]
text_columns = ["recent_note"]
date_columns = ["survey_date"]
print("Categorical Columns:", categorical_columns)
print("Text Columns:", text_columns)
print("Date Columns:", date_columns)

Categorical Columns: ['gender', 'education', 'role_seniority', 'company_size', 'location_tier']
Text Columns: ['recent_note']
Date Columns: ['survey_date']

In [14]:
target = "salary_bdt"
print("Target Variable:", target)

Target Variable: salary_bdt

In [15]:
print(df["survey_date"].head(10))
print("\nCurrent Data Type:", df["survey_date"].dtype)

0    2024-11-15
1    2024-03-08
2    2024-09-01
3    2024-01-26
4    2023-12-08
5    2023-09-17
6    2024-11-15
7    2023-06-23
8    2024-12-24
9    2023-07-14
Name: survey_date, dtype: str

Current Data Type: str

In [16]:
date_check = pd.to_datetime(
    df["survey_date"],
    errors="coerce"
)

print("Invalid date values:", date_check.isna().sum())

Invalid date values: 0

In [17]:
df["survey_date"] = pd.to_datetime(
    df["survey_date"],
    errors="coerce"
)

In [18]:
print(df["survey_date"].dtype)

datetime64[us]

In [19]:
df[["survey_date"]].head()

  survey_date
0  2024-11-15
1  2024-03-08
2  2024-09-01
3  2024-01-26
4  2023-12-08

In [20]:
print(df.dtypes)

age                                           int64
gender                                          str
education                                       str
experience_years                            float64
role_seniority                                  str
company_size                                    str
location_tier                                   str
skills_count                                float64
certifications                              float64
worked_remote                                 int64
last_promotion_years_ago                    float64
salary_bdt                                    int64
recent_project_description_length           float64
survey_date                          datetime64[us]
recent_note                                     str
dtype: object

In [21]:
df["survey_year"] = df["survey_date"].dt.year
df["survey_month"] = df["survey_date"].dt.month

In [22]:
df[["survey_date", "survey_year", "survey_month"]].head()

  survey_date  survey_year  survey_month
0  2024-11-15         2024            11
1  2024-03-08         2024             3
2  2024-09-01         2024             9
3  2024-01-26         2024             1
4  2023-12-08         2023            12

In [23]:
df = df.infer_objects()

In [24]:
print(df.dtypes)

age                                           int64
gender                                          str
education                                       str
experience_years                            float64
role_seniority                                  str
company_size                                    str
location_tier                                   str
skills_count                                float64
certifications                              float64
worked_remote                                 int64
last_promotion_years_ago                    float64
salary_bdt                                    int64
recent_project_description_length           float64
survey_date                          datetime64[us]
recent_note                                     str
survey_year                                   int32
survey_month                                  int32
dtype: object

In [25]:
print("Final Data Types:")
print(df.dtypes)

Final Data Types:
age                                           int64
gender                                          str
education                                       str
experience_years                            float64
role_seniority                                  str
company_size                                    str
location_tier                                   str
skills_count                                float64
certifications                              float64
worked_remote                                 int64
last_promotion_years_ago                    float64
salary_bdt                                    int64
recent_project_description_length           float64
survey_date                          datetime64[us]
recent_note                                     str
survey_year                                   int32
survey_month                                  int32
dtype: object

In [26]:
categorical_columns = [
    "gender",
    "education",
    "role_seniority",
    "company_size",
    "location_tier"
]

print("Categorical Columns:")
print(categorical_columns)

Categorical Columns:
['gender', 'education', 'role_seniority', 'company_size', 'location_tier']

In [27]:
for col in categorical_columns:
    print(f"\n{col}")
    print(df[col].unique())

gender
<ArrowStringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str

education
<ArrowStringArray>
['M.Sc', 'B.Sc+Cert', 'B.Sc', 'PhD', nan, 'M.Eng']
Length: 6, dtype: str

role_seniority
<ArrowStringArray>
['Senior', 'Junior', 'Lead', 'Mid']
Length: 4, dtype: str

company_size
<ArrowStringArray>
['Enterprise', 'SME', 'Startup']
Length: 3, dtype: str

location_tier
<ArrowStringArray>
['Tier-2', 'Remote', 'Tier-1', 'Tier-3']
Length: 4, dtype: str

In [28]:
for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- gender ---
gender
Male      1437
Female     530
Other       33
Name: count, dtype: int64

--- education ---
education
B.Sc         1070
M.Sc          445
B.Sc+Cert     229
NaN           100
M.Eng          99
PhD            57
Name: count, dtype: int64

--- role_seniority ---
role_seniority
Mid       791
Junior    715
Senior    393
Lead      101
Name: count, dtype: int64

--- company_size ---
company_size
SME           810
Startup       596
Enterprise    594
Name: count, dtype: int64

--- location_tier ---
location_tier
Tier-1    813
Tier-2    620
Remote    321
Tier-3    246
Name: count, dtype: int64

In [29]:
for col in categorical_columns:
    if df[col].dtype == "object":
        df[col] = df[col].str.strip()

In [30]:
for col in categorical_columns:
    print(f"\n{col}")
    print(df[col].unique())

gender
<ArrowStringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str

education
<ArrowStringArray>
['M.Sc', 'B.Sc+Cert', 'B.Sc', 'PhD', nan, 'M.Eng']
Length: 6, dtype: str

role_seniority
<ArrowStringArray>
['Senior', 'Junior', 'Lead', 'Mid']
Length: 4, dtype: str

company_size
<ArrowStringArray>
['Enterprise', 'SME', 'Startup']
Length: 3, dtype: str

location_tier
<ArrowStringArray>
['Tier-2', 'Remote', 'Tier-1', 'Tier-3']
Length: 4, dtype: str

In [31]:
for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- gender ---
gender
Male      1437
Female     530
Other       33
Name: count, dtype: int64

--- education ---
education
B.Sc         1070
M.Sc          445
B.Sc+Cert     229
NaN           100
M.Eng          99
PhD            57
Name: count, dtype: int64

--- role_seniority ---
role_seniority
Mid       791
Junior    715
Senior    393
Lead      101
Name: count, dtype: int64

--- company_size ---
company_size
SME           810
Startup       596
Enterprise    594
Name: count, dtype: int64

--- location_tier ---
location_tier
Tier-1    813
Tier-2    620
Remote    321
Tier-3    246
Name: count, dtype: int64

In [32]:
for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- gender ---
gender
Male      1437
Female     530
Other       33
Name: count, dtype: int64

--- education ---
education
B.Sc         1070
M.Sc          445
B.Sc+Cert     229
NaN           100
M.Eng          99
PhD            57
Name: count, dtype: int64

--- role_seniority ---
role_seniority
Mid       791
Junior    715
Senior    393
Lead      101
Name: count, dtype: int64

--- company_size ---
company_size
SME           810
Startup       596
Enterprise    594
Name: count, dtype: int64

--- location_tier ---
location_tier
Tier-1    813
Tier-2    620
Remote    321
Tier-3    246
Name: count, dtype: int64

In [33]:
for col in categorical_columns:
    if df[col].dtype == "object":
        df[col] = df[col].str.strip()

In [34]:
for col in categorical_columns:
    print(f"\n--- {col} ---")
    print("Unique values:", df[col].dropna().unique())
    print("Number of unique values:", df[col].nunique())

--- gender ---
Unique values: <ArrowStringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str
Number of unique values: 3

--- education ---
Unique values: <ArrowStringArray>
['M.Sc', 'B.Sc+Cert', 'B.Sc', 'PhD', 'M.Eng']
Length: 5, dtype: str
Number of unique values: 5

--- role_seniority ---
Unique values: <ArrowStringArray>
['Senior', 'Junior', 'Lead', 'Mid']
Length: 4, dtype: str
Number of unique values: 4

--- company_size ---
Unique values: <ArrowStringArray>
['Enterprise', 'SME', 'Startup']
Length: 3, dtype: str
Number of unique values: 3

--- location_tier ---
Unique values: <ArrowStringArray>
['Tier-2', 'Remote', 'Tier-1', 'Tier-3']
Length: 4, dtype: str
Number of unique values: 4

In [35]:
categorical_missing = df[categorical_columns].isnull().sum()

print(categorical_missing)

gender              0
education         100
role_seniority      0
company_size        0
location_tier       0
dtype: int64

In [36]:
for col in categorical_columns:
    print(f"\n{col}:")
    print(df[col].value_counts(dropna=False))

gender:
gender
Male      1437
Female     530
Other       33
Name: count, dtype: int64

education:
education
B.Sc         1070
M.Sc          445
B.Sc+Cert     229
NaN           100
M.Eng          99
PhD            57
Name: count, dtype: int64

role_seniority:
role_seniority
Mid       791
Junior    715
Senior    393
Lead      101
Name: count, dtype: int64

company_size:
company_size
SME           810
Startup       596
Enterprise    594
Name: count, dtype: int64

location_tier:
location_tier
Tier-1    813
Tier-2    620
Remote    321
Tier-3    246
Name: count, dtype: int64

In [37]:
for col in categorical_columns:
    print(f"\n--- {col} ---")
    print("Unique values:", df[col].dropna().unique())
    print("Number of unique values:", df[col].nunique())

--- gender ---
Unique values: <ArrowStringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str
Number of unique values: 3

--- education ---
Unique values: <ArrowStringArray>
['M.Sc', 'B.Sc+Cert', 'B.Sc', 'PhD', 'M.Eng']
Length: 5, dtype: str
Number of unique values: 5

--- role_seniority ---
Unique values: <ArrowStringArray>
['Senior', 'Junior', 'Lead', 'Mid']
Length: 4, dtype: str
Number of unique values: 4

--- company_size ---
Unique values: <ArrowStringArray>
['Enterprise', 'SME', 'Startup']
Length: 3, dtype: str
Number of unique values: 3

--- location_tier ---
Unique values: <ArrowStringArray>
['Tier-2', 'Remote', 'Tier-1', 'Tier-3']
Length: 4, dtype: str
Number of unique values: 4

In [38]:
categorical_missing = df[categorical_columns].isnull().sum()
print(categorical_missing)

gender              0
education         100
role_seniority      0
company_size        0
location_tier       0
dtype: int64

In [39]:
categorical_missing = df[categorical_columns].isnull().sum()
print(categorical_missing)

gender              0
education         100
role_seniority      0
company_size        0
location_tier       0
dtype: int64

In [40]:
seniority_mapping = {
    "Junior": 0,
    "Mid": 1,
    "Senior": 2,
    "Lead": 3
}

df["role_seniority_encoded"] = df["role_seniority"].map(
    seniority_mapping
)

In [41]:
df[
    ["role_seniority", "role_seniority_encoded"]
].drop_duplicates().sort_values("role_seniority_encoded")

  role_seniority  role_seniority_encoded
1         Junior                       0
3            Mid                       1
0         Senior                       2
2           Lead                       3

In [42]:
one_hot_columns = [
    "gender",
    "education",
    "company_size",
    "location_tier"
]
df_encoded = pd.get_dummies(
    df,
    columns=one_hot_columns,
    dummy_na=True,
    dtype=int
)

In [43]:
print(df_encoded.head())
print(df_encoded.columns.tolist())

   age  experience_years role_seniority  skills_count  certifications  \
0   33               6.0         Senior           1.0             2.0
1   29               9.0         Junior           5.0             0.0
2   34               NaN           Lead           5.0             1.0
3   39              16.0            Mid           5.0             0.0
4   29               8.0         Junior           5.0             2.0

   worked_remote  last_promotion_years_ago  salary_bdt  \
0              1                       0.0      145185
1              1                       0.0      121262
2              1                       5.0      184875
3              1                       3.0      180105
4              0                       7.0      114750

   recent_project_description_length survey_date  ... education_nan  \
0                               57.0  2024-11-15  ...             0
1                               50.0  2024-03-08  ...             0
2                               50.0  2024-09-01  ...             0
3                               59.0  2024-01-26  ...             0
4                                NaN  2023-12-08  ...             0

   company_size_Enterprise  company_size_SME  company_size_Startup  \
0                        1                 0                     0
1                        1                 0                     0
2                        1                 0                     0
3                        1                 0                     0
4                        0                 1                     0

   company_size_nan  location_tier_Remote  location_tier_Tier-1  \
0                 0                     0                     0
1                 0                     1                     0
2                 0                     1                     0
3                 0                     0                     1
4                 0                     0                     1

   location_tier_Tier-2  location_tier_Tier-3  location_tier_nan
0                     1                     0                  0
1                     0                     0                  0
2                     0                     0                  0
3                     0                     0                  0
4                     0                     0                  0

[5 rows x 33 columns]
['age', 'experience_years', 'role_seniority', 'skills_count', 'certifications', 'worked_remote', 'last_promotion_years_ago', 'salary_bdt', 'recent_project_description_length', 'survey_date', 'recent_note', 'survey_year', 'survey_month', 'role_seniority_encoded', 'gender_Female', 'gender_Male', 'gender_Other', 'gender_nan', 'education_B.Sc', 'education_B.Sc+Cert', 'education_M.Eng', 'education_M.Sc', 'education_PhD', 'education_nan', 'company_size_Enterprise', 'company_size_SME', 'company_size_Startup', 'company_size_nan', 'location_tier_Remote', 'location_tier_Tier-1', 'location_tier_Tier-2', 'location_tier_Tier-3', 'location_tier_nan']

In [44]:
print(df_encoded.dtypes)

age                                           int64
experience_years                            float64
role_seniority                                  str
skills_count                                float64
certifications                              float64
worked_remote                                 int64
last_promotion_years_ago                    float64
salary_bdt                                    int64
recent_project_description_length           float64
survey_date                          datetime64[us]
recent_note                                     str
survey_year                                   int32
survey_month                                  int32
role_seniority_encoded                        int64
gender_Female                                 int64
gender_Male                                   int64
gender_Other                                  int64
gender_nan                                    int64
education_B.Sc                                int64
education_B.Sc+Cert                           int64
education_M.Eng                               int64
education_M.Sc                                int64
education_PhD                                 int64
education_nan                                 int64
company_size_Enterprise                       int64
company_size_SME                              int64
company_size_Startup                          int64
company_size_nan                              int64
location_tier_Remote                          int64
location_tier_Tier-1                          int64
location_tier_Tier-2                          int64
location_tier_Tier-3                          int64
location_tier_nan                             int64
dtype: object

In [45]:
print("\nNon-numeric columns:")
print(
    df_encoded.select_dtypes(
        include=["object", "str"]
    ).columns.tolist()
)

Non-numeric columns:
['role_seniority', 'recent_note']

In [46]:
seniority_mapping = {
    "Junior": 0,
    "Mid": 1,
    "Senior": 2,
    "Lead": 3
}

df["role_seniority_encoded"] = df["role_seniority"].map(
    seniority_mapping
)

In [47]:
one_hot_columns = [
    "gender",
    "education",
    "company_size",
    "location_tier"
]

df_encoded = pd.get_dummies(
    df,
    columns=one_hot_columns,
    dummy_na=True,
    dtype=int
)

In [48]:
print(df_encoded.shape)
print(df_encoded.dtypes)

(2000, 33)
age                                           int64
experience_years                            float64
role_seniority                                  str
skills_count                                float64
certifications                              float64
worked_remote                                 int64
last_promotion_years_ago                    float64
salary_bdt                                    int64
recent_project_description_length           float64
survey_date                          datetime64[us]
recent_note                                     str
survey_year                                   int32
survey_month                                  int32
role_seniority_encoded                        int64
gender_Female                                 int64
gender_Male                                   int64
gender_Other                                  int64
gender_nan                                    int64
education_B.Sc                                int64
education_B.Sc+Cert                           int64
education_M.Eng                               int64
education_M.Sc                                int64
education_PhD                                 int64
education_nan                                 int64
company_size_Enterprise                       int64
company_size_SME                              int64
company_size_Startup                          int64
company_size_nan                              int64
location_tier_Remote                          int64
location_tier_Tier-1                          int64
location_tier_Tier-2                          int64
location_tier_Tier-3                          int64
location_tier_nan                             int64
dtype: object

In [49]:
df_encoded = df_encoded.drop(columns=["role_seniority"])

In [50]:
print(df_encoded.dtypes)

age                                           int64
experience_years                            float64
skills_count                                float64
certifications                              float64
worked_remote                                 int64
last_promotion_years_ago                    float64
salary_bdt                                    int64
recent_project_description_length           float64
survey_date                          datetime64[us]
recent_note                                     str
survey_year                                   int32
survey_month                                  int32
role_seniority_encoded                        int64
gender_Female                                 int64
gender_Male                                   int64
gender_Other                                  int64
gender_nan                                    int64
education_B.Sc                                int64
education_B.Sc+Cert                           int64
education_M.Eng                               int64
education_M.Sc                                int64
education_PhD                                 int64
education_nan                                 int64
company_size_Enterprise                       int64
company_size_SME                              int64
company_size_Startup                          int64
company_size_nan                              int64
location_tier_Remote                          int64
location_tier_Tier-1                          int64
location_tier_Tier-2                          int64
location_tier_Tier-3                          int64
location_tier_nan                             int64
dtype: object

In [51]:
one_hot_columns = [
    "gender",
    "education",
    "company_size",
    "location_tier"
]
df_encoded = pd.get_dummies(
    df.drop(columns=["role_seniority"]),
    columns=one_hot_columns,
    dummy_na=False,
    dtype=int
)

In [52]:
df_encoded = df.copy()
# Encode role seniority
df_encoded["role_seniority_encoded"] = df_encoded["role_seniority"].map({
    "Junior": 0,
    "Mid": 1,
    "Senior": 2,
    "Lead": 3
})
# Remove original categorical columns that will be encoded
df_encoded = df_encoded.drop(
    columns=[
        "role_seniority",
        "gender",
        "education",
        "company_size",
        "location_tier"
    ]
)
# One-hot encode categorical variables
categorical_to_encode = [
    "gender",
    "education",
    "company_size",
    "location_tier"
]
encoded_categories = pd.get_dummies(
    df[categorical_to_encode],
    columns=categorical_to_encode,
    dummy_na=False,
    dtype=int
)
# Add encoded columns
df_encoded = pd.concat(
    [df_encoded, encoded_categories],
    axis=1
)

In [53]:
print("Dataset Shape:", df.shape)
print("\nData Types:")
print(df.dtypes)
print("\nDate Column:")
print(df["survey_date"].dtype)
print("\nMissing Values:")
print(df.isnull().sum())

Dataset Shape: (2000, 18)

Data Types:
age                                           int64
gender                                          str
education                                       str
experience_years                            float64
role_seniority                                  str
company_size                                    str
location_tier                                   str
skills_count                                float64
certifications                              float64
worked_remote                                 int64
last_promotion_years_ago                    float64
salary_bdt                                    int64
recent_project_description_length           float64
survey_date                          datetime64[us]
recent_note                                     str
survey_year                                   int32
survey_month                                  int32
role_seniority_encoded                        int64
dtype: object

Date Column:
datetime64[us]

Missing Values:
age                                    0
gender                                 0
education                            100
experience_years                     160
role_seniority                         0
company_size                           0
location_tier                          0
skills_count                         200
certifications                        80
worked_remote                          0
last_promotion_years_ago             120
salary_bdt                             0
recent_project_description_length    240
survey_date                            0
recent_note                          300
survey_year                            0
survey_month                           0
role_seniority_encoded                 0
dtype: int64

In [54]:
df.to_csv("salary_task1_cleaned.csv", index=False)

In [55]:
import os

print(os.path.exists("salary_task1_cleaned.csv"))

True

In [56]:
import os

print(os.path.abspath("salary_task1_cleaned.csv"))

C:\Users\DELL\OneDrive\New folder\Desktop\brainybeam\18-09-26 tasks\salary_task1_cleaned.csv