In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [3]:
df = pd.read_csv("salary_task1_cleaned.csv")

print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())
df.head()

Dataset Shape: (2000, 18)

Columns:
['age', 'gender', 'education', 'experience_years', 'role_seniority', 'company_size', 'location_tier', 'skills_count', 'certifications', 'worked_remote', 'last_promotion_years_ago', 'salary_bdt', 'recent_project_description_length', 'survey_date', 'recent_note', 'survey_year', 'survey_month', 'role_seniority_encoded']

,age,gender,education,experience_years,role_seniority,company_size,location_tier,skills_count,certifications,worked_remote,last_promotion_years_ago,salary_bdt,recent_project_description_length,survey_date,recent_note,survey_year,survey_month,role_seniority_encoded
0,33,Male,M.Sc,6.0,Senior,Enterprise,Tier-2,1.0,2.0,1,0.0,145185,57.0,2024-11-15,Worked on microservices deployment,2024,11,2
1,29,Male,M.Sc,9.0,Junior,Enterprise,Remote,5.0,0.0,1,0.0,121262,50.0,2024-03-08,Built ML pipeline for preprocessing,2024,3,0
2,34,Male,B.Sc+Cert,NaN,Lead,Enterprise,Remote,5.0,1.0,1,5.0,184875,50.0,2024-09-01,Experience in data cleaning and ETL,2024,9,3
3,39,Male,B.Sc,16.0,Mid,Enterprise,Tier-1,5.0,0.0,1,3.0,180105,59.0,2024-01-26,Contributed to open-source NLP repo,2024,1,1
4,29,Female,B.Sc,8.0,Junior,SME,Tier-1,5.0,2.0,0,7.0,114750,NaN,2023-12-08,Built ML pipeline for preprocessing,2023,12,0

In [4]:
print("survey_date data type:")
print(df["survey_date"].dtype)

print("\nMissing values:")
print(df["survey_date"].isna().sum())

print("\nSample date values:")
print(df["survey_date"].head(20).to_list())

print("\nUnique date formats / examples:")
print(df["survey_date"].dropna().astype(str).sample(20, random_state=42).to_list())

survey_date data type:
str

Missing values:
0

Sample date values:
['2024-11-15', '2024-03-08', '2024-09-01', '2024-01-26', '2023-12-08', '2023-09-17', '2024-11-15', '2023-06-23', '2024-12-24', '2023-07-14', '2024-03-16', '2023-09-29', '2023-11-03', '2023-11-04', '2024-10-10', '2024-08-17', '2024-07-09', '2023-07-26', '2023-04-27', '2023-01-05']

Unique date formats / examples:
['2024-07-06', '2023-10-21', '2024-07-19', '2023-02-08', '2023-11-24', '2023-01-04', '2023-01-13', '2024-09-26', '2024-11-23', '2023-08-07', '2024-03-24', '2023-03-18', '2023-10-17', '2023-03-25', '2024-12-05', '2024-01-17', '2023-03-28', '2024-03-22', '2024-05-13', '2023-09-21']

In [5]:
df["survey_date"] = pd.to_datetime(
    df["survey_date"],
    errors="coerce"
)

print(df["survey_date"].dtype)

datetime64[us]

In [6]:
invalid_dates = df["survey_date"].isna().sum()

print("Invalid / unparseable dates:", invalid_dates)

Invalid / unparseable dates: 0

In [7]:
df["survey_year"] = df["survey_date"].dt.year
df["survey_month"] = df["survey_date"].dt.month
df["survey_day"] = df["survey_date"].dt.day
df["survey_quarter"] = df["survey_date"].dt.quarter
df["survey_day_of_week"] = df["survey_date"].dt.day_name()

In [8]:
df[
    [
        "survey_date",
        "survey_year",
        "survey_month",
        "survey_day",
        "survey_quarter",
        "survey_day_of_week"
    ]
].head(10)

,survey_date,survey_year,survey_month,survey_day,survey_quarter,survey_day_of_week
0,2024-11-15,2024,11,15,4,Friday
1,2024-03-08,2024,3,8,1,Friday
2,2024-09-01,2024,9,1,3,Sunday
3,2024-01-26,2024,1,26,1,Friday
4,2023-12-08,2023,12,8,4,Friday
5,2023-09-17,2023,9,17,3,Sunday
6,2024-11-15,2024,11,15,4,Friday
7,2023-06-23,2023,6,23,2,Friday
8,2024-12-24,2024,12,24,4,Tuesday
9,2023-07-14,2023,7,14,3,Friday

In [11]:
raw_dates = pd.read_csv("salary_task1_cleaned.csv")

raw_dates["survey_date_original"] = raw_dates["survey_date"].astype(str)

raw_dates["parsed_date"] = pd.to_datetime(
    raw_dates["survey_date_original"],
    errors="coerce"
)

invalid_mask = raw_dates["parsed_date"].isna()

print("Total dates:", len(raw_dates))
print("Invalid dates:", invalid_mask.sum())

Total dates: 2000
Invalid dates: 0

In [12]:
if invalid_mask.sum() > 0:
    print("\nInvalid date values:")
    print(raw_dates.loc[invalid_mask, "survey_date_original"])
else:
    print("No invalid date values found.")

No invalid date values found.

In [13]:
today = pd.Timestamp.today().normalize()

future_dates = df["survey_date"] > today

print("Today's date:", today.date())
print("Future dates:", future_dates.sum())

Today's date: 2026-08-23
Future dates: 0

In [14]:
print("Timezone information:")
print(df["survey_date"].dt.tz)

Timezone information:
None

In [15]:
timezone_status = "No timezone information present in survey_date"

print(timezone_status)

No timezone information present in survey_date

In [16]:
def normalize_datetime(value):
    """
    Convert a date/time value into a consistent UTC-aware timestamp.
    Invalid values return NaT.
    """
    try:
        dt = pd.to_datetime(value, errors="coerce", utc=True)
        return dt
    except Exception:
        return pd.NaT

In [17]:
test_dates = [
    "2024-11-15",
    "2024-11-15 10:30:00",
    "2024-11-15 10:30:00+05:30",
    "2024-11-15 05:00:00+00:00",
    "invalid-date"
]

for value in test_dates:
    print(value, "->", normalize_datetime(value))

2024-11-15 -> 2024-11-15 00:00:00+00:00
2024-11-15 10:30:00 -> 2024-11-15 10:30:00+00:00
2024-11-15 10:30:00+05:30 -> 2024-11-15 05:00:00+00:00
2024-11-15 05:00:00+00:00 -> 2024-11-15 05:00:00+00:00
invalid-date -> NaT

In [18]:
df["estimated_joining_date"] = (
    df["survey_date"] -
    pd.to_timedelta(df["experience_years"] * 365.25, unit="D")
)

In [19]:
df[
    [
        "survey_date",
        "experience_years",
        "estimated_joining_date"
    ]
].head(10)

  survey_date  experience_years estimated_joining_date
0  2024-11-15               6.0    2018-11-15 12:00:00
1  2024-03-08               9.0    2015-03-08 18:00:00
2  2024-09-01               NaN                    NaT
3  2024-01-26              16.0    2008-01-26 00:00:00
4  2023-12-08               8.0    2015-12-08 00:00:00
5  2023-09-17               7.0    2016-09-16 06:00:00
6  2024-11-15              19.0    2005-11-15 06:00:00
7  2023-06-23              10.0    2013-06-22 12:00:00
8  2024-12-24               4.0    2020-12-24 00:00:00
9  2023-07-14              12.0    2011-07-14 00:00:00

In [20]:
df["joining_year"] = df["estimated_joining_date"].dt.year
df["joining_month"] = df["estimated_joining_date"].dt.month
df["joining_day"] = df["estimated_joining_date"].dt.day
df["joining_quarter"] = df["estimated_joining_date"].dt.quarter
df["joining_day_of_week"] = df["estimated_joining_date"].dt.day_name()

In [21]:
df[
    [
        "estimated_joining_date",
        "joining_year",
        "joining_month",
        "joining_day",
        "joining_quarter",
        "joining_day_of_week"
    ]
].head(10)

,estimated_joining_date,joining_year,joining_month,joining_day,joining_quarter,joining_day_of_week
0,2018-11-15 12:00:00,2018.0,11.0,15.0,4.0,Thursday
1,2015-03-08 18:00:00,2015.0,3.0,8.0,1.0,Sunday
2,NaT,NaN,NaN,NaN,NaN,NaN
3,2008-01-26 00:00:00,2008.0,1.0,26.0,1.0,Saturday
4,2015-12-08 00:00:00,2015.0,12.0,8.0,4.0,Tuesday
5,2016-09-16 06:00:00,2016.0,9.0,16.0,3.0,Friday
6,2005-11-15 06:00:00,2005.0,11.0,15.0,4.0,Tuesday
7,2013-06-22 12:00:00,2013.0,6.0,22.0,2.0,Saturday
8,2020-12-24 00:00:00,2020.0,12.0,24.0,4.0,Thursday
9,2011-07-14 00:00:00,2011.0,7.0,14.0,3.0,Thursday

In [22]:
today = pd.Timestamp.today().normalize()

df["tenure_years"] = (
    (today - df["estimated_joining_date"]).dt.days / 365.25
)

In [23]:
df["tenure_years"] = df["tenure_years"].round(2)

In [24]:
df[
    [
        "estimated_joining_date",
        "tenure_years"
    ]
].head(10)

  estimated_joining_date  tenure_years
0    2018-11-15 12:00:00          7.77
1    2015-03-08 18:00:00         11.46
2                    NaT           NaN
3    2008-01-26 00:00:00         18.57
4    2015-12-08 00:00:00         10.71
5    2016-09-16 06:00:00          9.93
6    2005-11-15 06:00:00         20.77
7    2013-06-22 12:00:00         13.17
8    2020-12-24 00:00:00          5.66
9    2011-07-14 00:00:00         15.11

In [25]:
df["tenure_months"] = (
    df["tenure_years"] * 12
).round().astype("Int64")

In [26]:
df[
    [
        "estimated_joining_date",
        "tenure_years",
        "tenure_months"
    ]
].head(10)

  estimated_joining_date  tenure_years  tenure_months
0    2018-11-15 12:00:00          7.77             93
1    2015-03-08 18:00:00         11.46            138
2                    NaT           NaN           <NA>
3    2008-01-26 00:00:00         18.57            223
4    2015-12-08 00:00:00         10.71            129
5    2016-09-16 06:00:00          9.93            119
6    2005-11-15 06:00:00         20.77            249
7    2013-06-22 12:00:00         13.17            158
8    2020-12-24 00:00:00          5.66             68
9    2011-07-14 00:00:00         15.11            181

In [27]:
print("Minimum tenure:", df["tenure_years"].min())
print("Maximum tenure:", df["tenure_years"].max())

print(
    "Negative tenure records:",
    (df["tenure_years"] < 0).sum()
)

Minimum tenure: 1.67
Maximum tenure: 31.87
Negative tenure records: 0

In [28]:
comparison = df[
    [
        "experience_years",
        "tenure_years"
    ]
].describe()

comparison

       experience_years  tenure_years
count       1840.000000   1840.000000
mean           7.729348     10.385076
std            5.676872      5.710235
min            0.000000      1.670000
25%            3.000000      5.720000
50%            7.000000      9.995000
75%           11.000000     14.072500
max           29.000000     31.870000

In [29]:
df[
    [
        "experience_years",
        "estimated_joining_date",
        "tenure_years"
    ]
].head(20)

    experience_years estimated_joining_date  tenure_years
0                6.0    2018-11-15 12:00:00          7.77
1                9.0    2015-03-08 18:00:00         11.46
2                NaN                    NaT           NaN
3               16.0    2008-01-26 00:00:00         18.57
4                8.0    2015-12-08 00:00:00         10.71
5                7.0    2016-09-16 06:00:00          9.93
6               19.0    2005-11-15 06:00:00         20.77
7               10.0    2013-06-22 12:00:00         13.17
8                4.0    2020-12-24 00:00:00          5.66
9               12.0    2011-07-14 00:00:00         15.11
10               7.0    2017-03-16 06:00:00          9.43
11               1.0    2022-09-28 18:00:00          3.90
12               4.0    2019-11-03 00:00:00          6.80
13               0.0    2023-11-04 00:00:00          2.80
14               0.0    2024-10-10 00:00:00          1.87
15               0.0    2024-08-17 00:00:00          2.02
16               0.0    2024-07-09 00:00:00          2.12
17              10.0    2013-07-25 12:00:00         13.08
18               9.0    2014-04-26 18:00:00         12.32
19               0.0    2023-01-05 00:00:00          3.63

In [30]:
df["tenure_category"] = pd.cut(
    df["tenure_years"],
    bins=[-1, 2, 5, 10, 20, np.inf],
    labels=[
        "0-2 Years",
        "3-5 Years",
        "6-10 Years",
        "11-20 Years",
        "20+ Years"
    ]
)

In [31]:
df["tenure_category"].value_counts()

tenure_category
11-20 Years    803
6-10 Years     516
3-5 Years      369
20+ Years      116
0-2 Years       36
Name: count, dtype: int64

In [32]:
print("Final Dataset Shape:", df.shape)

print("\nMissing Values:")
print(
    df[
        [
            "survey_date",
            "estimated_joining_date",
            "joining_year",
            "joining_month",
            "tenure_years"
        ]
    ].isna().sum()
)

print("\nFinal Date Columns:")
print(
    df[
        [
            "survey_date",
            "estimated_joining_date",
            "joining_year",
            "joining_month",
            "joining_day",
            "tenure_years",
            "tenure_months",
            "tenure_category"
        ]
    ].head()
)

Final Dataset Shape: (2000, 30)

Missing Values:
survey_date                 0
estimated_joining_date    160
joining_year              160
joining_month             160
tenure_years              160
dtype: int64

Final Date Columns:
  survey_date estimated_joining_date  joining_year  joining_month  \
0  2024-11-15    2018-11-15 12:00:00        2018.0           11.0
1  2024-03-08    2015-03-08 18:00:00        2015.0            3.0
2  2024-09-01                    NaT           NaN            NaN
3  2024-01-26    2008-01-26 00:00:00        2008.0            1.0
4  2023-12-08    2015-12-08 00:00:00        2015.0           12.0

   joining_day  tenure_years  tenure_months tenure_category
0         15.0          7.77             93      6-10 Years
1          8.0         11.46            138     11-20 Years
2          NaN           NaN           <NA>             NaN
3         26.0         18.57            223     11-20 Years
4          8.0         10.71            129     11-20 Years

In [33]:
output_file = "salary_task2_date_processed.csv"

df.to_csv(
    output_file,
    index=False
)

print(f"Dataset saved successfully as: {output_file}")

Dataset saved successfully as: salary_task2_date_processed.csv